
# The URL the site will be built for
base_url = "https://destratified.github.io"

theme = "terminus"
title = "ink the ghost"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

taxonomies = [
    { name = "tags", feed = true },
    { name = "categories", feed = true, paginate_by = 5 },
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here

#main menu tabs for pages blog, all tags listed in front-matter and about
main_menu = [
    { name = "blog", url = "blog", trailing_slash = true },
    { name = "tags", url = "tags", trailing_slash = true },
    { name = "about", url = "about", trailing_slash = true },
]

# Author name: when specified, modifies the default
# copyright text. Apart from author, it will
# contain current year and a link to the theme.
author = "970uts1d3"


favicon = "/icons/favicon.png"
favicon_mimetype = "image/png"   
